// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQd3ywC_ZirSncHrFVaxoNrgjIyLNlMwk',
    appId: '1:573170828780:web:59c04f2d6fb56e7a712cc9',
    messagingSenderId: '573170828780',
    projectId: 'wasalny-app-b3ad0',
    authDomain: 'wasalny-app-b3ad0.firebaseapp.com',
    storageBucket: 'wasalny-app-b3ad0.firebasestorage.app',
    measurementId: 'G-W0YT896B4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiuTuEt4Af7VYIDGivA2bMY-ondJ3ygcM',
    appId: '1:573170828780:android:f384d651cbb52dd4712cc9',
    messagingSenderId: '573170828780',
    projectId: 'wasalny-app-b3ad0',
    storageBucket: 'wasalny-app-b3ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKemwQgc2j9Mgldsf1S9EtgPlorDXK4cA',
    appId: '1:573170828780:ios:cb8fdfd729586f22712cc9',
    messagingSenderId: '573170828780',
    projectId: 'wasalny-app-b3ad0',
    storageBucket: 'wasalny-app-b3ad0.firebasestorage.app',
    iosBundleId: 'com.example.wasalnyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKemwQgc2j9Mgldsf1S9EtgPlorDXK4cA',
    appId: '1:573170828780:ios:cb8fdfd729586f22712cc9',
    messagingSenderId: '573170828780',
    projectId: 'wasalny-app-b3ad0',
    storageBucket: 'wasalny-app-b3ad0.firebasestorage.app',
    iosBundleId: 'com.example.wasalnyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQd3ywC_ZirSncHrFVaxoNrgjIyLNlMwk',
    appId: '1:573170828780:web:7d59f614f83df1ca712cc9',
    messagingSenderId: '573170828780',
    projectId: 'wasalny-app-b3ad0',
    authDomain: 'wasalny-app-b3ad0.firebaseapp.com',
    storageBucket: 'wasalny-app-b3ad0.firebasestorage.app',
    measurementId: 'G-32GWWGRDT6',
  );
}
